name: xml_query_test_driver
description: A driver for the XQuery/XPath 3.* Test Suite
version: 0.0.1
#author: Peter <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  xml: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
